/**
 * Salon 21 client rate-card catalog (men + women + nails).
 * Each length / wax-type / product variant is its own billable service
 * because ServiceMaster has a single price.
 *
 * Duration minutes are operational defaults for booking slots (not on the PDF).
 */

function svc(category, name, price, duration_minutes = 30) {
  return { category, name, price, duration_minutes };
}

export const CLIENT_SERVICE_CATEGORIES = [
  "Makeup & Bridal",
  "Threading",
  "Face Wax",
  "Women Regular Wax",
  "Women Flavoured Wax",
  "Women Roll-on Wax",
  "Women Bleach",
  "Women D-Tan",
  "Women Polishing",
  "Women D-Tan with Scrubbing",
  "Women Clean Ups",
  "Women Add-on Masks",
  "Women Basic Facials",
  "Women Advanced Facials",
  "Women Facial Treatments",
  "Women Body Care",
  "Women Pedicure",
  "Women Manicure",
  "Women Beauty Add-ons",
  "Women Haircut & Styling",
  "Women Head Massage & Boosts",
  "Women Hair Spa & Rituals",
  "Women Global Colour",
  "Women Colour Techniques",
  "Women Hair Treatments",
  "Men Hair & Beard",
  "Men Head Massage",
  "Men Spa & Treatments",
  "Men Regular Wax",
  "Men Flavoured Wax",
  "Men Roll-on Wax",
  "Men Body Care",
  "Men Hair Treatments",
  "Nail Studio",
];

/** @type {{ category: string, name: string, price: number, duration_minutes: number }[]} */
export const CLIENT_SERVICES = [
  // ── Makeup & Bridal ──────────────────────────────────────────────
  svc("Makeup & Bridal", "Airbrush Bridal Makeup & Style", 20000, 180),
  svc("Makeup & Bridal", "HD Bridal Makeup", 12000, 150),
  svc("Makeup & Bridal", "Haldi & Sangeet Look", 7000, 90),
  svc("Makeup & Bridal", "Engagement Look", 7000, 90),
  svc("Makeup & Bridal", "Reception Look", 7000, 90),
  svc("Makeup & Bridal", "Baby Shower Look", 6000, 90),
  svc("Makeup & Bridal", "Party Makeup", 5000, 75),
  svc("Makeup & Bridal", "Pre-Wedding Shoot", 10000, 120),
  svc("Makeup & Bridal", "Destination Wedding", 40000, 240),
  svc("Makeup & Bridal", "Groom Makeup", 5000, 75),
  svc("Makeup & Bridal", "Basic Hair Style", 1500, 45),
  svc("Makeup & Bridal", "Advanced Hair Style", 3500, 75),
  svc("Makeup & Bridal", "Saree Draping", 500, 30),
  svc("Makeup & Bridal", "Basic Makeup & Style", 3000, 60),

  // ── Threading ────────────────────────────────────────────────────
  svc("Threading", "Eyebrows Threading", 40, 10),
  svc("Threading", "Upper Lips Threading", 30, 10),
  svc("Threading", "Lower Lips Threading", 30, 10),
  svc("Threading", "Forehead Threading", 50, 10),
  svc("Threading", "Chin Threading", 30, 10),
  svc("Threading", "Jawline Threading", 60, 15),
  svc("Threading", "Full Face Threading", 200, 25),

  // ── Face Wax ─────────────────────────────────────────────────────
  svc("Face Wax", "Eyebrows Face Wax", 100, 10),
  svc("Face Wax", "Upper Lips Face Wax", 100, 10),
  svc("Face Wax", "Lower Lips Face Wax", 100, 10),
  svc("Face Wax", "Forehead Face Wax", 100, 10),
  svc("Face Wax", "Chin Face Wax", 120, 10),
  svc("Face Wax", "Jawline Face Wax", 150, 15),
  svc("Face Wax", "Side Blocks Face Wax", 250, 20),
  svc("Face Wax", "Full Face Wax", 550, 30),
  svc("Face Wax", "Nose Wax", 100, 10),

  // ── Women Regular Wax ────────────────────────────────────────────
  svc("Women Regular Wax", "Full Arms Regular Wax", 300, 30),
  svc("Women Regular Wax", "Half Arms Regular Wax", 200, 20),
  svc("Women Regular Wax", "Full Legs Regular Wax", 400, 40),
  svc("Women Regular Wax", "Half Legs Regular Wax", 300, 25),
  svc("Women Regular Wax", "Underarms Regular Wax", 100, 15),
  svc("Women Regular Wax", "Full Front Regular Wax", 400, 35),
  svc("Women Regular Wax", "Half Front Regular Wax", 250, 25),
  svc("Women Regular Wax", "Full Back Regular Wax", 400, 35),
  svc("Women Regular Wax", "Half Back Regular Wax", 250, 25),
  svc("Women Regular Wax", "Stomach Regular Wax", 200, 20),
  svc("Women Regular Wax", "B Wax Regular", 1000, 45),
  svc("Women Regular Wax", "Bikini Line Regular Wax", 600, 30),
  svc("Women Regular Wax", "Butt Wax Regular", 600, 30),
  svc("Women Regular Wax", "Full Body Regular Wax", 2000, 90),

  // ── Women Flavoured Wax ──────────────────────────────────────────
  svc("Women Flavoured Wax", "Full Arms Flavoured Wax", 400, 30),
  svc("Women Flavoured Wax", "Half Arms Flavoured Wax", 300, 20),
  svc("Women Flavoured Wax", "Full Legs Flavoured Wax", 700, 40),
  svc("Women Flavoured Wax", "Half Legs Flavoured Wax", 400, 25),
  svc("Women Flavoured Wax", "Underarms Flavoured Wax", 150, 15),
  svc("Women Flavoured Wax", "Brazilian Underarms Flavoured Wax", 200, 15),
  svc("Women Flavoured Wax", "Full Front Flavoured Wax", 700, 35),
  svc("Women Flavoured Wax", "Half Front Flavoured Wax", 400, 25),
  svc("Women Flavoured Wax", "Full Back Flavoured Wax", 700, 35),
  svc("Women Flavoured Wax", "Half Back Flavoured Wax", 400, 25),
  svc("Women Flavoured Wax", "Stomach Flavoured Wax", 400, 20),
  svc("Women Flavoured Wax", "B Wax Flavoured", 1500, 45),
  svc("Women Flavoured Wax", "Brazilian B Wax Flavoured", 1700, 50),
  svc("Women Flavoured Wax", "Bikini Flavoured Wax", 800, 30),
  svc("Women Flavoured Wax", "Butt Flavoured Wax", 800, 30),
  svc("Women Flavoured Wax", "Full Body Flavoured Wax", 3500, 100),

  // ── Women Roll-on Wax ────────────────────────────────────────────
  svc("Women Roll-on Wax", "Full Hand Roll-on Wax", 500, 30),
  svc("Women Roll-on Wax", "Half Hand Roll-on Wax", 400, 20),
  svc("Women Roll-on Wax", "Full Leg Roll-on Wax", 800, 40),
  svc("Women Roll-on Wax", "Half Leg Roll-on Wax", 500, 25),
  svc("Women Roll-on Wax", "Underarms Roll-on Wax", 200, 15),
  svc("Women Roll-on Wax", "Full Front Roll-on Wax", 800, 35),
  svc("Women Roll-on Wax", "Half Front Roll-on Wax", 500, 25),
  svc("Women Roll-on Wax", "Full Back Roll-on Wax", 800, 35),
  svc("Women Roll-on Wax", "Half Back Roll-on Wax", 500, 25),
  svc("Women Roll-on Wax", "Stomach Roll-on Wax", 500, 20),
  svc("Women Roll-on Wax", "Bikini Line Roll-on Wax", 900, 30),
  svc("Women Roll-on Wax", "Butt Wax Roll-on", 900, 30),
  svc("Women Roll-on Wax", "Full Body Roll-on Wax", 4500, 100),

  // ── Women Bleach ─────────────────────────────────────────────────
  svc("Women Bleach", "Face & Neck Bleach", 600, 30),
  svc("Women Bleach", "Full Arms Bleach", 700, 40),
  svc("Women Bleach", "Half Arms Bleach", 300, 25),
  svc("Women Bleach", "Full Leg Bleach", 1000, 45),
  svc("Women Bleach", "Half Leg Bleach", 400, 30),
  svc("Women Bleach", "Underarms Bleach", 300, 20),
  svc("Women Bleach", "Full Front Bleach", 1200, 45),
  svc("Women Bleach", "Half Front Bleach", 600, 30),
  svc("Women Bleach", "Full Back Bleach", 1200, 45),
  svc("Women Bleach", "Half Back Bleach", 600, 30),
  svc("Women Bleach", "Stomach Bleach", 600, 25),
  svc("Women Bleach", "B Wax Area Bleach", 600, 25),
  svc("Women Bleach", "Bikini Line Bleach", 300, 20),
  svc("Women Bleach", "Full Body Bleach", 5500, 120),

  // ── Women D-Tan ──────────────────────────────────────────────────
  svc("Women D-Tan", "Face & Neck D-Tan O3", 800, 40),
  svc("Women D-Tan", "Face & Neck D-Tan RAGA", 700, 40),
  svc("Women D-Tan", "Full Arms D-Tan", 800, 40),
  svc("Women D-Tan", "Half Arms D-Tan", 500, 25),
  svc("Women D-Tan", "Full Leg D-Tan", 1000, 45),
  svc("Women D-Tan", "Half Leg D-Tan", 600, 30),
  svc("Women D-Tan", "Underarms D-Tan", 300, 20),
  svc("Women D-Tan", "Full Front D-Tan", 1300, 45),
  svc("Women D-Tan", "Half Front D-Tan", 800, 30),
  svc("Women D-Tan", "Full Back D-Tan", 1300, 45),
  svc("Women D-Tan", "Half Back D-Tan", 800, 30),
  svc("Women D-Tan", "Stomach D-Tan", 1000, 30),
  svc("Women D-Tan", "B Wax Area D-Tan", 800, 25),
  svc("Women D-Tan", "Bikini Line D-Tan", 500, 20),
  svc("Women D-Tan", "Full Body D-Tan", 6500, 120),

  // ── Women Polishing ──────────────────────────────────────────────
  svc("Women Polishing", "Underarms Polishing", 500, 20),
  svc("Women Polishing", "Full Hand Polishing", 1200, 40),
  svc("Women Polishing", "Half Hand Polishing", 900, 30),
  svc("Women Polishing", "Full Leg Polishing", 1600, 50),
  svc("Women Polishing", "Half Leg Polishing", 1200, 35),
  svc("Women Polishing", "Full Back Polishing", 2000, 50),
  svc("Women Polishing", "Full Body Basic Polishing", 4000, 90),
  svc("Women Polishing", "Full Body Advanced Polishing", 7000, 120),

  // ── Women D-Tan with Scrubbing ───────────────────────────────────
  svc("Women D-Tan with Scrubbing", "Underarms D-Tan Scrub", 300, 20),
  svc("Women D-Tan with Scrubbing", "Full Hand D-Tan Scrub", 1000, 40),
  svc("Women D-Tan with Scrubbing", "Half Hand D-Tan Scrub", 700, 30),
  svc("Women D-Tan with Scrubbing", "Full Leg D-Tan Scrub", 1500, 50),
  svc("Women D-Tan with Scrubbing", "Half Leg D-Tan Scrub", 900, 35),
  svc("Women D-Tan with Scrubbing", "Full Back D-Tan Scrub", 1500, 45),
  svc("Women D-Tan with Scrubbing", "Half Back D-Tan Scrub", 1000, 30),
  svc("Women D-Tan with Scrubbing", "Full Front D-Tan Scrub", 1500, 45),
  svc("Women D-Tan with Scrubbing", "Half Front D-Tan Scrub", 1000, 30),

  // ── Women Clean Ups ──────────────────────────────────────────────
  svc("Women Clean Ups", "Clean Up", 800, 45),
  svc("Women Clean Ups", "O3 Whitening Clean Up", 1000, 50),
  svc("Women Clean Ups", "Fruit Clean Up", 1300, 50),
  svc("Women Clean Ups", "O3 Seaweed Revitalization", 1500, 60),
  svc("Women Clean Ups", "Hydra Clean Up", 2000, 60),

  // ── Women Add-on Masks ───────────────────────────────────────────
  svc("Women Add-on Masks", "Eye Need Blink Mask", 150, 15),
  svc("Women Add-on Masks", "Hydrating Lip Mask", 150, 15),
  svc("Women Add-on Masks", "B Mask", 500, 20),
  svc("Women Add-on Masks", "Ultra Hydrating Mask", 500, 20),
  svc("Women Add-on Masks", "Instant Glow Mask", 500, 20),
  svc("Women Add-on Masks", "Black Mask", 900, 25),
  svc("Women Add-on Masks", "Collagen Mask", 2500, 30),

  // ── Women Basic Facials ──────────────────────────────────────────
  svc("Women Basic Facials", "Fruit Facial", 1000, 45),
  svc("Women Basic Facials", "Instant Glow Facial", 1800, 50),
  svc("Women Basic Facials", "Sericalm Facial", 2200, 60),
  svc("Women Basic Facials", "O3 Whitening Facial", 2200, 60),
  svc("Women Basic Facials", "Serenite Men's Facial", 2500, 60),
  svc("Women Basic Facials", "Good Bye Tan — Vedic", 3000, 60),
  svc("Women Basic Facials", "Vitamin C — Vedic", 3500, 60),
  svc("Women Basic Facials", "Serenite Radiant Glow", 4000, 75),

  // ── Women Advanced Facials ───────────────────────────────────────
  svc("Women Advanced Facials", "Korean Ritual Radiant Glass Skin", 4500, 75),
  svc("Women Advanced Facials", "O3 Hydra Ritual", 5000, 75),
  svc("Women Advanced Facials", "O3 AGELOCK Anti-Aging", 5500, 90),
  svc("Women Advanced Facials", "Serenite Ultra Bright", 5000, 75),
  svc("Women Advanced Facials", "Serenite Pomegranate Luxury Facial", 5500, 90),
  svc("Women Advanced Facials", "Hydra Organic Radiant Facial", 6000, 90),
  svc("Women Advanced Facials", "Organic Brightening Facial", 6500, 90),
  svc("Women Advanced Facials", "Bridal Facial Ritual", 7000, 90),

  // ── Women Facial Treatments ──────────────────────────────────────
  svc("Women Facial Treatments", "Eye Treatment", 3000, 45),
  svc("Women Facial Treatments", "Acne Treatment", 7500, 75),
  svc("Women Facial Treatments", "Wrinkles Treatment", 8000, 75),
  svc("Women Facial Treatments", "Pigmentation Treatment", 7000, 75),
  svc("Women Facial Treatments", "Brightening & Smoothening Peel", 7000, 60),

  // ── Women Body Care ──────────────────────────────────────────────
  svc("Women Body Care", "Herbal Body Polishing Basic", 4000, 90),
  svc("Women Body Care", "Advanced Body Polishing", 7000, 120),
  svc("Women Body Care", "Relaxing Body Massage", 2000, 60),
  svc("Women Body Care", "Back Massage", 800, 30),
  svc("Women Body Care", "Face Massage", 700, 25),

  // ── Women Pedicure ───────────────────────────────────────────────
  svc("Women Pedicure", "Change of Polish (Pedicure)", 100, 15),
  svc("Women Pedicure", "Cut, File & Polish (Pedicure)", 200, 25),
  svc("Women Pedicure", "Not So Regular Pedicure", 700, 45),
  svc("Women Pedicure", "Marvelicious Pedicure", 1000, 50),
  svc("Women Pedicure", "Lavender Pedicure", 1000, 50),
  svc("Women Pedicure", "Honey Comb Apple Pedicure", 1200, 55),
  svc("Women Pedicure", "Vitamin C Pedicure", 1200, 55),
  svc("Women Pedicure", "Tata Tan Pedicure", 1800, 60),
  svc("Women Pedicure", "Tan Go Mintree Pedicure", 2500, 70),
  svc("Women Pedicure", "Ice Cream Pedicure", 2000, 65),
  svc("Women Pedicure", "Luxury Box The Tox Pedicure", 3000, 75),

  // ── Women Manicure ───────────────────────────────────────────────
  svc("Women Manicure", "Dry Manicure", 300, 30),
  svc("Women Manicure", "Not So Regular Manicure", 600, 40),
  svc("Women Manicure", "Marvelicious Manicure", 900, 45),
  svc("Women Manicure", "Lavender Manicure", 900, 45),
  svc("Women Manicure", "Honey Comb Apple Manicure", 1000, 50),
  svc("Women Manicure", "Vitamin C Manicure", 1000, 50),
  svc("Women Manicure", "Tata Tan Manicure", 1700, 55),
  svc("Women Manicure", "Tan Go Mintree Manicure", 2300, 60),
  svc("Women Manicure", "Ice Cream Manicure", 1900, 55),
  svc("Women Manicure", "Luxury Box The Tox Manicure", 3000, 70),

  // ── Women Beauty Add-ons ─────────────────────────────────────────
  svc("Women Beauty Add-ons", "Machine Cleansing", 200, 20),
  svc("Women Beauty Add-ons", "Hand Glows", 450, 25),
  svc("Women Beauty Add-ons", "Feet Glows", 450, 25),
  svc("Women Beauty Add-ons", "Foot Massage", 700, 30),
  svc("Women Beauty Add-ons", "Foot Reflexology", 1000, 40),

  // ── Women Haircut & Styling ──────────────────────────────────────
  svc("Women Haircut & Styling", "Fringe Cut", 200, 15),
  svc("Women Haircut & Styling", "Hair Trimming", 500, 30),
  svc("Women Haircut & Styling", "Stylist Haircut (Women)", 700, 45),
  svc("Women Haircut & Styling", "Senior Stylist Haircut (Women)", 700, 45),
  svc("Women Haircut & Styling", "Creative Director Haircut (Women)", 1000, 60),
  svc("Women Haircut & Styling", "Kids Haircut (Under 10)", 250, 30),
  svc("Women Haircut & Styling", "Kids with Wash", 450, 40),
  svc("Women Haircut & Styling", "Kids Haircut + Wash + Blow Dry", 700, 50),
  svc("Women Haircut & Styling", "Wash & Blow Dry — Shoulder", 450, 40),
  svc("Women Haircut & Styling", "Wash & Blow Dry — Mid Back", 500, 45),
  svc("Women Haircut & Styling", "Wash & Blow Dry — Waist", 600, 50),
  svc("Women Haircut & Styling", "Wash & Plain Dry — Shoulder", 300, 30),
  svc("Women Haircut & Styling", "Wash & Plain Dry — Mid Back", 350, 35),
  svc("Women Haircut & Styling", "Wash & Plain Dry — Waist", 400, 40),
  svc("Women Haircut & Styling", "Blow Dry — Shoulder", 300, 30),
  svc("Women Haircut & Styling", "Blow Dry — Mid Back", 400, 35),
  svc("Women Haircut & Styling", "Blow Dry — Waist & Below", 500, 40),
  svc("Women Haircut & Styling", "Crimping / Ironing — Mid Back", 600, 40),
  svc("Women Haircut & Styling", "Crimping / Ironing — Waist", 700, 45),
  svc("Women Haircut & Styling", "Tongs & Roller — Shoulder", 700, 45),
  svc("Women Haircut & Styling", "Tongs & Roller — Waist & Below", 800, 50),
  svc("Women Haircut & Styling", "Moroccan Glaze — Up to Shoulder", 900, 45),
  svc("Women Haircut & Styling", "Moroccan Glaze — Up to Mid Back", 1100, 50),
  svc("Women Haircut & Styling", "Moroccan Glaze — Waist & Below", 1300, 55),

  // ── Women Head Massage & Boosts ──────────────────────────────────
  svc("Women Head Massage & Boosts", "Oil Massage (Coconut / Almond / Navratna) — Women", 400, 30),
  svc("Women Head Massage & Boosts", "Ayurvedic Oil Massage (Olive Oil) — Women", 600, 35),
  svc("Women Head Massage & Boosts", "Moroccan Oil Massage — Women", 800, 40),
  svc("Women Head Massage & Boosts", "10 Min Extra Massage — Women", 200, 10),
  svc("Women Head Massage & Boosts", "Extra Product Used — Women", 200, 5),
  svc("Women Head Massage & Boosts", "Smooth Boost", 500, 30),
  svc("Women Head Massage & Boosts", "Health Boost", 500, 30),
  svc("Women Head Massage & Boosts", "Shimmer Boost", 500, 30),
  svc("Women Head Massage & Boosts", "Moisturize Boost", 500, 30),
  svc("Women Head Massage & Boosts", "Volume Boost", 500, 30),
  svc("Women Head Massage & Boosts", "Scrubbing With Wash", 700, 40),

  // ── Women Hair Spa & Rituals ─────────────────────────────────────
  svc("Women Hair Spa & Rituals", "Insta Care Spa — Women", 900, 45),
  svc("Women Hair Spa & Rituals", "Just For You Destress — Women", 1200, 50),
  svc("Women Hair Spa & Rituals", "Just For You Enhance — Women", 1200, 50),
  svc("Women Hair Spa & Rituals", "Protein Spa — Women", 1700, 60),
  svc("Women Hair Spa & Rituals", "Moroccan Spa — Women", 3500, 75),
  svc("Women Hair Spa & Rituals", "Hair Growth Treatment — Women", 1500, 60),
  svc("Women Hair Spa & Rituals", "Anti-Dandruff — Women", 1500, 50),
  svc("Women Hair Spa & Rituals", "Naturica Spa — Women", 3000, 70),
  svc("Women Hair Spa & Rituals", "Beauty Sutra Oil Spa — Women", 3300, 70),
  svc("Women Hair Spa & Rituals", "K18 Treatment — Women", 2500, 60),
  svc("Women Hair Spa & Rituals", "K18 Mask — Women", 1800, 45),
  svc("Women Hair Spa & Rituals", "Essential Oil Scalp Treatment — Women", 1500, 45),
  svc("Women Hair Spa & Rituals", "Extra Length (Hair Spa Add-on)", 300, 10),
  svc("Women Hair Spa & Rituals", "Dandruff Ritual", 3300, 75),
  svc("Women Hair Spa & Rituals", "Hair Fall Ritual", 3300, 75),
  svc("Women Hair Spa & Rituals", "Repair Ritual", 2000, 60),
  svc("Women Hair Spa & Rituals", "Moisturising Ritual", 2000, 60),
  svc("Women Hair Spa & Rituals", "Infusions Rennovador Caviar Ritual", 4000, 90),
  svc("Women Hair Spa & Rituals", "Fiberplex 5ML", 700, 20),
  svc("Women Hair Spa & Rituals", "Fiberplex 10ML", 1200, 25),

  // ── Women Global Colour ──────────────────────────────────────────
  svc("Women Global Colour", "Global Colour With Ammonia — Shoulder", 4000, 90),
  svc("Women Global Colour", "Global Colour With Ammonia — Below Shoulder", 5500, 105),
  svc("Women Global Colour", "Global Colour With Ammonia — Waist", 6500, 120),
  svc("Women Global Colour", "Global Highlights With Ammonia — Shoulder", 4500, 100),
  svc("Women Global Colour", "Global Highlights With Ammonia — Below Shoulder", 5800, 115),
  svc("Women Global Colour", "Global Highlights With Ammonia — Waist", 6500, 130),
  svc("Women Global Colour", "Global Colour Ammonia Free — Shoulder", 5000, 90),
  svc("Women Global Colour", "Global Colour Ammonia Free — Below Shoulder", 6000, 105),
  svc("Women Global Colour", "Global Colour Ammonia Free — Waist", 6800, 120),
  svc("Women Global Colour", "Global Highlights Ammonia Free — Shoulder", 5000, 100),
  svc("Women Global Colour", "Global Highlights Ammonia Free — Below Shoulder", 6000, 115),
  svc("Women Global Colour", "Global Highlights Ammonia Free — Waist", 6800, 130),
  svc("Women Global Colour", "Naturica Vegan Global Colour — Shoulder", 6000, 90),
  svc("Women Global Colour", "Naturica Vegan Global Colour — Below Shoulder", 7200, 105),
  svc("Women Global Colour", "Naturica Vegan Global Colour — Waist", 8160, 120),
  svc("Women Global Colour", "Naturica Vegan Global Highlights — Shoulder", 6000, 100),
  svc("Women Global Colour", "Naturica Vegan Global Highlights — Below Shoulder", 7200, 115),
  svc("Women Global Colour", "Naturica Vegan Global Highlights — Waist", 8160, 130),

  // ── Women Colour Techniques ──────────────────────────────────────
  svc("Women Colour Techniques", "Naturica Root Touch-up (Vegan) — 1 Inch", 2000, 45),
  svc("Women Colour Techniques", "Naturica Root Touch-up (Vegan) — 2 Inch", 2300, 50),
  svc("Women Colour Techniques", "Naturica Root Touch-up (Vegan) — 3 Inch", 2500, 55),
  svc("Women Colour Techniques", "Colour Root Touch-up (With Ammonia) — 1 Inch", 1300, 40),
  svc("Women Colour Techniques", "Colour Root Touch-up (With Ammonia) — 2 Inch", 1600, 45),
  svc("Women Colour Techniques", "Colour Root Touch-up (With Ammonia) — 3 Inch", 1800, 50),
  svc("Women Colour Techniques", "Ammonia-Free Root Touch-up — 1 Inch", 1300, 40),
  svc("Women Colour Techniques", "Ammonia-Free Root Touch-up — 2 Inch", 1600, 45),
  svc("Women Colour Techniques", "Ammonia-Free Root Touch-up — 3 Inch", 1800, 50),
  svc("Women Colour Techniques", "Crown Highlights (5 Foils) — Up to Shoulder", 1500, 45),
  svc("Women Colour Techniques", "Crown Highlights (5 Foils) — Below Shoulder", 2000, 55),
  svc("Women Colour Techniques", "Crown Highlights (5 Foils) — Up to Waist", 2500, 65),
  svc("Women Colour Techniques", "T-Section Highlights (10 Foils) — Up to Shoulder", 3000, 60),
  svc("Women Colour Techniques", "T-Section Highlights (10 Foils) — Below Shoulder", 4000, 75),
  svc("Women Colour Techniques", "T-Section Highlights (10 Foils) — Up to Waist", 4500, 90),
  svc("Women Colour Techniques", "Gentle Cleansing (Colour Remover) — Up to Shoulder", 1500, 45),
  svc("Women Colour Techniques", "Gentle Cleansing (Colour Remover) — Below Shoulder", 1800, 55),
  svc("Women Colour Techniques", "Gentle Cleansing (Colour Remover) — Up to Waist", 2000, 65),
  svc("Women Colour Techniques", "Colour Toning — Up to Shoulder", 2000, 40),
  svc("Women Colour Techniques", "Colour Toning — Below Shoulder", 2500, 50),
  svc("Women Colour Techniques", "Colour Toning — Up to Waist", 3000, 60),
  svc("Women Colour Techniques", "Pre-Light Highlight (Per Strand) — Up to Shoulder", 500, 20),
  svc("Women Colour Techniques", "Pre-Light Highlight (Per Strand) — Below Shoulder", 600, 25),
  svc("Women Colour Techniques", "Pre-Light Highlight (Per Strand) — Up to Waist", 700, 30),
  svc("Women Colour Techniques", "Colour Per Foil — Up to Shoulder", 300, 15),
  svc("Women Colour Techniques", "Colour Per Foil — Below Shoulder", 400, 15),
  svc("Women Colour Techniques", "Colour Per Foil — Up to Waist", 500, 15),
  svc("Women Colour Techniques", "Glitter (Per Strand)", 30, 10),

  // ── Women Hair Treatments ────────────────────────────────────────
  svc("Women Hair Treatments", "Cystine — Fringe", 1900, 45),
  svc("Women Hair Treatments", "Cystine — Shoulder", 6500, 90),
  svc("Women Hair Treatments", "Cystine — Below Shoulder", 7500, 105),
  svc("Women Hair Treatments", "Cystine — Waist", 8500, 120),
  svc("Women Hair Treatments", "Protein Botox — Fringe", 3000, 50),
  svc("Women Hair Treatments", "Protein Botox — Shoulder", 9000, 120),
  svc("Women Hair Treatments", "Protein Botox — Below Shoulder", 11500, 135),
  svc("Women Hair Treatments", "Protein Botox — Waist", 13000, 150),
  svc("Women Hair Treatments", "Botoplastia — Fringe", 2500, 50),
  svc("Women Hair Treatments", "Botoplastia — Shoulder", 7000, 105),
  svc("Women Hair Treatments", "Botoplastia — Below Shoulder", 9000, 120),
  svc("Women Hair Treatments", "Botoplastia — Waist", 10000, 135),
  svc("Women Hair Treatments", "QUD Treatment — Fringe", 2500, 50),
  svc("Women Hair Treatments", "QUD Treatment — Shoulder", 7000, 105),
  svc("Women Hair Treatments", "QUD Treatment — Below Shoulder", 9000, 120),
  svc("Women Hair Treatments", "QUD Treatment — Waist", 10000, 135),
  svc("Women Hair Treatments", "Straightening — Fringe", 2000, 45),
  svc("Women Hair Treatments", "Straightening — Shoulder", 5000, 90),
  svc("Women Hair Treatments", "Straightening — Below Shoulder", 7000, 105),
  svc("Women Hair Treatments", "Straightening — Waist", 8000, 120),
  svc("Women Hair Treatments", "Smoothening — Fringe", 1800, 45),
  svc("Women Hair Treatments", "Smoothening — Shoulder", 4500, 90),
  svc("Women Hair Treatments", "Smoothening — Below Shoulder", 6500, 105),
  svc("Women Hair Treatments", "Smoothening — Waist", 7500, 120),

  // ── Men Hair & Beard ─────────────────────────────────────────────
  svc("Men Hair & Beard", "Stylist Haircut (Men)", 250, 30),
  svc("Men Hair & Beard", "Senior Stylist Haircut (Men)", 250, 30),
  svc("Men Hair & Beard", "Creative Director Haircut (Men)", 300, 40),
  svc("Men Hair & Beard", "Kids Haircut 10+", 200, 25),
  svc("Men Hair & Beard", "Kids Haircut Under 10", 150, 20),
  svc("Men Hair & Beard", "Wash & Hair Set", 150, 25),
  svc("Men Hair & Beard", "Wash Only", 100, 15),
  svc("Men Hair & Beard", "Long Hair Wash", 250, 20),
  svc("Men Hair & Beard", "Face Wash", 100, 10),
  svc("Men Hair & Beard", "Clean Shave", 100, 15),
  svc("Men Hair & Beard", "Beard Trimming", 150, 15),
  svc("Men Hair & Beard", "Beard Styling", 150, 20),
  svc("Men Hair & Beard", "Beard Colour", 350, 30),
  svc("Men Hair & Beard", "Long-Length Beard Colour", 800, 40),
  svc("Men Hair & Beard", "Moustache Colour", 100, 10),

  // ── Men Head Massage ─────────────────────────────────────────────
  svc("Men Head Massage", "Oil Massage (Coconut / Almond / Navratna) — Men", 350, 30),
  svc("Men Head Massage", "Ayurvedic Oil Massage (Olive Oil) — Men", 450, 35),
  svc("Men Head Massage", "Moroccan Oil Massage — Men", 600, 40),
  svc("Men Head Massage", "10 Min Extra Massage — Men", 200, 10),
  svc("Men Head Massage", "Extra Product Used — Men", 200, 5),

  // ── Men Spa & Treatments ─────────────────────────────────────────
  svc("Men Spa & Treatments", "Insta Care Spa — Men", 600, 40),
  svc("Men Spa & Treatments", "Just For You Destress — Men", 900, 45),
  svc("Men Spa & Treatments", "Just For You Enhance — Men", 900, 45),
  svc("Men Spa & Treatments", "Protein Spa — Men", 1300, 55),
  svc("Men Spa & Treatments", "Moroccan Spa — Men", 2300, 70),
  svc("Men Spa & Treatments", "Hair Growth Treatment — Men", 1200, 50),
  svc("Men Spa & Treatments", "Beauty Sutra Oil Spa — Men", 2000, 60),
  svc("Men Spa & Treatments", "Anti-Dandruff — Men", 1200, 45),
  svc("Men Spa & Treatments", "Naturica Spa — Men", 1800, 60),
  svc("Men Spa & Treatments", "Caviar Ritual — Men", 2500, 70),
  svc("Men Spa & Treatments", "Essential Oil Scalp Treatment — Men", 1200, 45),
  svc("Men Spa & Treatments", "Essential Sensitive Treatment — Men", 1200, 45),
  svc("Men Spa & Treatments", "K18 Treatment — Men", 1500, 50),
  svc("Men Spa & Treatments", "K18 Mask — Men", 1000, 40),
  svc("Men Spa & Treatments", "Extra Product / Long Length — Men", 200, 10),

  // ── Men Regular Wax ──────────────────────────────────────────────
  svc("Men Regular Wax", "Full Hand Regular Wax — Men", 500, 30),
  svc("Men Regular Wax", "Half Hand Regular Wax — Men", 400, 20),
  svc("Men Regular Wax", "Full Leg Regular Wax — Men", 600, 40),
  svc("Men Regular Wax", "Half Leg Regular Wax — Men", 500, 25),
  svc("Men Regular Wax", "Underarms Regular Wax — Men", 150, 15),
  svc("Men Regular Wax", "Full Cheeks Regular Wax — Men", 600, 30),
  svc("Men Regular Wax", "Half Cheeks Regular Wax — Men", 450, 20),
  svc("Men Regular Wax", "Full Back Regular Wax — Men", 600, 35),
  svc("Men Regular Wax", "Half Back Regular Wax — Men", 450, 25),

  // ── Men Flavoured Wax ────────────────────────────────────────────
  svc("Men Flavoured Wax", "Full Hand Flavoured Wax — Men", 600, 30),
  svc("Men Flavoured Wax", "Half Hand Flavoured Wax — Men", 500, 20),
  svc("Men Flavoured Wax", "Full Leg Flavoured Wax — Men", 1000, 40),
  svc("Men Flavoured Wax", "Half Leg Flavoured Wax — Men", 800, 25),
  svc("Men Flavoured Wax", "Underarms Flavoured Wax — Men", 250, 15),
  svc("Men Flavoured Wax", "Full Cheeks Flavoured Wax — Men", 1200, 35),
  svc("Men Flavoured Wax", "Half Cheeks Flavoured Wax — Men", 700, 25),
  svc("Men Flavoured Wax", "Full Back Flavoured Wax — Men", 1200, 40),
  svc("Men Flavoured Wax", "Half Back Flavoured Wax — Men", 700, 25),

  // ── Men Roll-on Wax ──────────────────────────────────────────────
  svc("Men Roll-on Wax", "Full Hand Roll-on Wax — Men", 700, 30),
  svc("Men Roll-on Wax", "Half Hand Roll-on Wax — Men", 600, 20),
  svc("Men Roll-on Wax", "Full Leg Roll-on Wax — Men", 1100, 40),
  svc("Men Roll-on Wax", "Half Leg Roll-on Wax — Men", 900, 25),
  svc("Men Roll-on Wax", "Underarms Roll-on Wax — Men", 350, 15),
  svc("Men Roll-on Wax", "Full Front Roll-on Wax — Men", 1300, 40),
  svc("Men Roll-on Wax", "Half Front Roll-on Wax — Men", 800, 25),
  svc("Men Roll-on Wax", "Full Back Roll-on Wax — Men", 1300, 40),
  svc("Men Roll-on Wax", "Half Back Roll-on Wax — Men", 800, 25),

  // ── Men Body Care ────────────────────────────────────────────────
  svc("Men Body Care", "Face & Neck D-Tan O3 — Men", 800, 40),
  svc("Men Body Care", "Face & Neck D-Tan RAGA — Men", 700, 40),
  svc("Men Body Care", "Full Hand D-Tan — Men", 1000, 40),
  svc("Men Body Care", "Half Hand D-Tan — Men", 700, 30),
  svc("Men Body Care", "Full Leg D-Tan — Men", 1500, 50),
  svc("Men Body Care", "Half Leg D-Tan — Men", 900, 35),
  svc("Men Body Care", "Full Back D-Tan — Men", 1500, 45),
  svc("Men Body Care", "Half Back D-Tan — Men", 1000, 30),
  svc("Men Body Care", "Underarms Polishing — Men", 500, 20),
  svc("Men Body Care", "Full Hand Polishing — Men", 1500, 40),
  svc("Men Body Care", "Half Hand Polishing — Men", 900, 30),
  svc("Men Body Care", "Full Leg Polishing — Men", 2000, 50),
  svc("Men Body Care", "Half Leg Polishing — Men", 1400, 35),
  svc("Men Body Care", "Full Back Polishing — Men", 2500, 50),
  svc("Men Body Care", "Full Body Polishing Basic — Men", 4000, 90),
  svc("Men Body Care", "Full Body Polishing Advance — Men", 7000, 120),

  // ── Men Hair Treatments ──────────────────────────────────────────
  svc("Men Hair Treatments", "Straightening — Very Short (Men)", 2300, 60),
  svc("Men Hair Treatments", "Straightening — Medium (Men)", 2800, 75),
  svc("Men Hair Treatments", "Straightening — Shoulder (Men)", 3500, 90),
  svc("Men Hair Treatments", "Smoothening — Very Short (Men)", 2000, 55),
  svc("Men Hair Treatments", "Smoothening — Medium (Men)", 2500, 70),
  svc("Men Hair Treatments", "Smoothening — Shoulder (Men)", 3000, 85),
  svc("Men Hair Treatments", "Global Colour With Ammonia — Very Short (Men)", 1000, 45),
  svc("Men Hair Treatments", "Global Colour With Ammonia — Medium (Men)", 1600, 60),
  svc("Men Hair Treatments", "Global Colour With Ammonia — Shoulder (Men)", 2500, 75),
  svc("Men Hair Treatments", "Global Highlights With Ammonia — Very Short (Men)", 1200, 50),
  svc("Men Hair Treatments", "Global Highlights With Ammonia — Medium (Men)", 1800, 65),
  svc("Men Hair Treatments", "Global Highlights With Ammonia — Shoulder (Men)", 3000, 80),
  svc("Men Hair Treatments", "Global Colour Ammonia Free — Very Short (Men)", 1000, 45),
  svc("Men Hair Treatments", "Global Colour Ammonia Free — Medium (Men)", 1600, 60),
  svc("Men Hair Treatments", "Global Colour Ammonia Free — Shoulder (Men)", 2500, 75),
  svc("Men Hair Treatments", "Global Highlights Ammonia Free — Very Short (Men)", 1200, 50),
  svc("Men Hair Treatments", "Global Highlights Ammonia Free — Medium (Men)", 1800, 65),
  svc("Men Hair Treatments", "Global Highlights Ammonia Free — Shoulder (Men)", 3000, 80),
  svc("Men Hair Treatments", "Naturica Vegan Colour — Very Short (Men)", 1300, 45),
  svc("Men Hair Treatments", "Naturica Vegan Colour — Medium (Men)", 2000, 60),
  svc("Men Hair Treatments", "Naturica Vegan Colour — Shoulder (Men)", 3600, 75),

  // ── Nail Studio ──────────────────────────────────────────────────
  svc("Nail Studio", "Acrylic Extension + Gel Polish", 2000, 90),
  svc("Nail Studio", "Temporary Extension + Gel Polish", 1300, 75),
  svc("Nail Studio", "Refilling + Gel Polish", 1500, 60),
  svc("Nail Studio", "Feet Extension + Gel Polish", 1500, 75),
  svc("Nail Studio", "Natural Nails Gel Polish — Hands", 700, 45),
  svc("Nail Studio", "Natural Nails Gel Polish — Feet", 700, 45),
  svc("Nail Studio", "Gel Polish Removal", 150, 20),
  svc("Nail Studio", "Acrylic Extension Removal", 250, 25),
  svc("Nail Studio", "One Finger Nail Art", 100, 10),
];
