"""
Generate Salon Management System Implementation Tracker (XLSX + CSV).
Format mirrors MPBCDC_Implementation_Tracker reference.
"""
from __future__ import annotations

import csv
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

OUTPUT_DIR = Path(__file__).resolve().parents[1]
XLSX_PATH = OUTPUT_DIR / "Salon-Management-System-Implementation-Tracker.xlsx"
CSV_DIR = OUTPUT_DIR / "implementation-tracker-csv"

HEADERS = [
    "Section",
    "Sub-Section",
    "Item / Task",
    "Layer",
    "Detail / Expected Result",
    "Status",
    "Assigned Dev",
    "Priority",
    "Sprint / Phase",
    "Notes",
]

# Row tuple: section, sub_section, task, layer, detail, status, dev, priority, phase, notes
# Use None for section headers (will be rendered as section-only rows)


def section(title: str) -> tuple:
    return (title, None, None, None, None, None, None, None, None, None)


def task(
    section_name: str,
    sub: str,
    item: str,
    layer: str,
    detail: str,
    dev: str,
    priority: str = "High",
    phase: str = "Phase 1",
    status: str = "Not Started",
    notes: str | None = None,
) -> tuple:
    return (section_name, sub, item, layer, detail, status, dev, priority, phase, notes)


SHEETS: dict[str, list[tuple]] = {}

# ---------------------------------------------------------------------------
# 01 Architecture-Foundation
# ---------------------------------------------------------------------------
SHEETS["01 Architecture-Foundation"] = [
    section("1. TECHNOLOGY STACK"),
    task(
        "Stack",
        "Monorepo",
        "Project scaffold (backend/ + frontend/)",
        "All",
        "Root package.json scripts; backend Node+Express .js; frontend React+Vite .jsx; .env.example for MONGO_URI, JWT_SECRET, PORT.",
        "Arnav",
        "Critical",
        "Phase 0",
        notes="Precious clones after scaffold merged — do not scaffold in parallel.",
    ),
    task(
        "Stack",
        "Frontend",
        "React 18 + Vite setup (frontend/)",
        "Frontend",
        "Single responsive codebase; PWA-ready vite-plugin-pwa config stub; mobile-first breakpoints.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Stack",
        "Backend",
        "Node.js + Express API setup (backend/)",
        "Backend",
        "REST API; folders: models/, routes/, controllers/, services/, middleware/, seeds/, utils/.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Stack",
        "Database",
        "MongoDB + Mongoose connection",
        "DB",
        "config/db.js; health check endpoint GET /api/health.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Stack",
        "Auth",
        "JWT auth (login, refresh pattern)",
        "Backend",
        "POST /api/auth/login; Bearer token; password_hash on User; POST /api/auth/me returns user + permissions.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Stack",
        "Charts",
        "Chart.js (or Recharts) integration",
        "Frontend",
        "Shared chart wrappers in frontend/src/components/charts/ for dashboard reuse.",
        "Arnav",
        "Medium",
        "Phase 2",
    ),
    task(
        "Stack",
        "PWA",
        "vite-plugin-pwa manifest + service worker",
        "Frontend",
        "Installable PWA; add-to-homescreen; offline shell for login page only (Phase 2 polish).",
        "Precious",
        "Medium",
        "Phase 2",
        notes="Precious owns PWA files: vite.config PWA block, manifest icons — no overlap with Arnav pages.",
    ),
    section("2. FOLDER STRUCTURE & MERGE-SAFE ROUTING"),
    task(
        "Architecture",
        "Route split",
        "backend/routes/arnavRoutes.js",
        "Backend",
        "Arnav mounts all own module routes here; index.js only imports arnavRoutes + preciousRoutes.",
        "Arnav",
        "Critical",
        "Phase 0",
        notes="Avoids both devs editing routes/index.js.",
    ),
    task(
        "Architecture",
        "Route split",
        "backend/routes/preciousRoutes.js",
        "Backend",
        "Precious mounts billing, attendance, packages, whatsapp routes here.",
        "Precious",
        "Critical",
        "Phase 0",
    ),
    task(
        "Architecture",
        "Route split",
        "frontend/src/routes/arnavRoutes.jsx",
        "Frontend",
        "Lazy-loaded routes for auth, dashboard, bookings, CRM, payroll, reports (Arnav modules).",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Architecture",
        "Route split",
        "frontend/src/routes/preciousRoutes.jsx",
        "Frontend",
        "Lazy-loaded routes for billing, attendance, packages, campaigns, inventory reports.",
        "Precious",
        "Critical",
        "Phase 0",
    ),
    task(
        "Architecture",
        "App shell",
        "ERP shell layout (collapsible left nav)",
        "Frontend",
        "Layout.jsx, Sidebar.jsx, TopBar.jsx — Celeris/AIMS style; menu items driven by permissions API.",
        "Arnav",
        "Critical",
        "Phase 0",
        notes="Precious does not edit Layout/Sidebar — adds menu entries via permission seeds only.",
    ),
    task(
        "Architecture",
        "API client",
        "frontend/src/api/client.js + module API files",
        "Frontend",
        "Axios instance with auth interceptor; split api/arnav/ and api/precious/ subfolders per owner.",
        "Arnav",
        "High",
        "Phase 0",
    ),
    task(
        "Architecture",
        "Branch schema",
        "models/Branch.js",
        "DB",
        "Single branch seeded; branch_id on User, Booking, Invoice; schema supports multi-branch later.",
        "Arnav",
        "High",
        "Phase 0",
    ),
    task(
        "Architecture",
        "Error handling",
        "Global error middleware + API response envelope",
        "Backend",
        "Consistent { success, data, message } shape; 4xx/5xx handlers.",
        "Arnav",
        "Medium",
        "Phase 0",
    ),
    task(
        "Architecture",
        "Transactions",
        "Mongo multi-document transaction helper",
        "Backend",
        "utils/withTransaction.js for billing+package redemption+commission atomic writes.",
        "Precious",
        "Critical",
        "Phase 1",
        notes="Used primarily in billing/package flows owned by Precious.",
    ),
    task(
        "Architecture",
        "Audit log",
        "models/AuditLog.js + write helper",
        "Backend",
        "Log stock overrides, discount overrides, package redemptions, payroll finalize, permission changes.",
        "Arnav",
        "Medium",
        "Phase 1",
    ),
    section("3. SEED DATA & DEV SETUP"),
    task(
        "Seeds",
        "Branch",
        "seed/branchSeed.js — default salon branch",
        "DB",
        "One active branch row for dev/staging.",
        "Arnav",
        "High",
        "Phase 0",
    ),
    task(
        "Seeds",
        "Roles",
        "seed/rolePermissionSeed.js",
        "DB",
        "Seed Owner/CEO, Manager, Stylist, Massage/Spa Therapist + all Permission rows + RolePermission map.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Seeds",
        "Owner user",
        "seed/ownerUserSeed.js",
        "DB",
        "Default CEO login for dev; temp password in README (not committed).",
        "Arnav",
        "High",
        "Phase 0",
    ),
    task(
        "Seeds",
        "Demo data",
        "seed/demoDataSeed.js (services, products, staff)",
        "DB",
        "Optional sample masters for UI dev after modules built.",
        "Both",
        "Low",
        "Phase 1",
        notes="Split: Arnav seeds services/products; Precious seeds staff/shifts — separate seed files.",
    ),
]

# ---------------------------------------------------------------------------
# 02 RBAC-User-Management (Arnav owns entirely)
# ---------------------------------------------------------------------------
SHEETS["02 RBAC-User-Management"] = [
    section("STEP ZERO — ROLES & PERMISSIONS (BUILD BEFORE FEATURE MODULES)"),
    task(
        "RBAC",
        "DB",
        "models/Role.js",
        "DB",
        "Fields: name, description. Seed 4 roles: Owner/CEO, Manager, Stylist, Massage/Spa Therapist.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "DB",
        "models/Permission.js",
        "DB",
        "Fields: module, action (view|create|edit|delete|approve). One row per module+action combo.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "DB",
        "models/RolePermission.js",
        "DB",
        "Many-to-many role_id + permission_id; drives dynamic left-nav.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "DB",
        "models/UserMenuOverride.js",
        "DB",
        "user_id, permission_id, granted boolean — CEO per-user permission override.",
        "Arnav",
        "High",
        "Phase 0",
    ),
    task(
        "RBAC",
        "DB",
        "models/User.js",
        "DB",
        "name, phone, email, password_hash, role_id, branch_id, is_active, created_by, created_at.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "Backend",
        "middleware/requirePermission.js",
        "Backend",
        "requirePermission(module, action) — 403 if missing; resolves RolePermission + UserMenuOverride.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "Backend",
        "GET /api/auth/permissions (or /me)",
        "Backend",
        "Returns resolved permission set for session; frontend builds menu from this.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "Frontend",
        "hooks/usePermission.js — hasPermission(module, action)",
        "Frontend",
        "Central helper; NO scattered if(role==='owner') checks across codebase.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "Frontend",
        "PermissionContext.jsx",
        "Frontend",
        "Loads permissions at login; provides to Sidebar and route guards.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "RBAC",
        "Frontend",
        "ProtectedRoute.jsx",
        "Frontend",
        "Redirect to login; optional module+action gate per route.",
        "Arnav",
        "High",
        "Phase 0",
    ),
    section("USER MANAGEMENT (OWNER/CEO ONLY)"),
    task(
        "User Mgmt",
        "Backend",
        "CRUD /api/users",
        "Backend",
        "Create user (name, phone, role); soft-deactivate (is_active=false); never hard-delete with history.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "User Mgmt",
        "Backend",
        "PUT /api/users/:id/permission-overrides",
        "Backend",
        "CEO toggles individual UserMenuOverride rows.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "User Mgmt",
        "Backend",
        "Temp password + invite stub",
        "Backend",
        "Auto-generate temp password on create; hook for WhatsApp invite (Precious wires sender later).",
        "Arnav",
        "Medium",
        "Phase 1",
    ),
    task(
        "User Mgmt",
        "Frontend",
        "pages/users/UserList.jsx",
        "Frontend",
        "List users with role, status; Owner/CEO only.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "User Mgmt",
        "Frontend",
        "pages/users/UserForm.jsx",
        "Frontend",
        "Create/edit user, role dropdown, activate/deactivate.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "User Mgmt",
        "Frontend",
        "pages/users/UserPermissionOverrides.jsx",
        "Frontend",
        "Per-user permission toggle grid.",
        "Arnav",
        "Medium",
        "Phase 1",
    ),
    task(
        "User Mgmt",
        "Frontend",
        "pages/auth/Login.jsx",
        "Frontend",
        "Phone/Email + Password; single login URL for all roles; post-login redirect by permissions.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    section("STYLIST / THERAPIST SELF-SERVICE VIEWS"),
    task(
        "Staff Portal",
        "Frontend",
        "pages/staff/MyCalendar.jsx (view only)",
        "Frontend",
        "Stylist/Therapist sees own bookings calendar only.",
        "Arnav",
        "Medium",
        "Phase 1",
        notes="Uses booking API read-only; separate file from Precious attendance views.",
    ),
    task(
        "Staff Portal",
        "Frontend",
        "pages/staff/MyEarnings.jsx",
        "Frontend",
        "Own commission/earnings view for Stylist/Therapist roles.",
        "Arnav",
        "Medium",
        "Phase 2",
    ),
]

# ---------------------------------------------------------------------------
# 03 Masters-Settings (split ownership)
# ---------------------------------------------------------------------------
SHEETS["03 Masters-Settings"] = [
    section("ARNAV — SERVICE, PRODUCT, TAX MASTERS"),
    task(
        "Service Master",
        "DB",
        "models/ServiceCategory.js, models/ServiceMaster.js",
        "DB",
        "Category: name. Service: category_id, name, duration_minutes, price, commission_slab_override_id, is_active.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Service Master",
        "Backend",
        "CRUD /api/service-categories, /api/services",
        "Backend",
        "routes/serviceRoutes.js in arnavRoutes.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Service Master",
        "Frontend",
        "pages/settings/services/ServiceList.jsx, ServiceForm.jsx",
        "Frontend",
        "Settings > Services; category filter; duration/price/commission override.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Product Master",
        "DB",
        "models/ProductMaster.js",
        "DB",
        "name, sku, unit, purchase_price, sale_price, current_stock, reorder_level, is_active.",
        "Arnav",
        "Critical",
        "Phase 1",
        notes="Precious reads stock via API in billing — does not edit this model.",
    ),
    task(
        "Product Master",
        "Backend",
        "CRUD /api/products",
        "Backend",
        "Includes GET low-stock list for dashboard alerts.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Product Master",
        "Frontend",
        "pages/settings/products/ProductList.jsx, ProductForm.jsx",
        "Frontend",
        "Stock level display; reorder level field.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Tax/GST Master",
        "DB",
        "models/TaxMaster.js",
        "DB",
        "name, rate, applies_to (service|product|both), is_active.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Tax/GST Master",
        "Backend",
        "CRUD /api/taxes",
        "Backend",
        "Used by billing service (Precious consumes).",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Tax/GST Master",
        "Frontend",
        "pages/settings/tax/TaxList.jsx, TaxForm.jsx",
        "Frontend",
        "Separate rates for services vs products.",
        "Arnav",
        "Medium",
        "Phase 1",
    ),
    section("PRECIOUS — STAFF, SHIFT, PACKAGE MASTERS"),
    task(
        "Staff Master",
        "DB",
        "models/StaffProfile.js, models/CommissionSlab.js",
        "DB",
        "StaffProfile: user_id, designation, specialization[], commission_slab_id, base_salary, shift_id, joining_date. CommissionSlab: name, type, rules_json.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Staff Master",
        "Backend",
        "CRUD /api/staff, /api/commission-slabs",
        "Backend",
        "routes/staffRoutes.js in preciousRoutes; filter stylists by specialization for bookings API consumer.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Staff Master",
        "Frontend",
        "pages/settings/staff/StaffList.jsx, StaffForm.jsx",
        "Frontend",
        "Link to User; specialization multi-select; salary, shift, commission slab.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Shift/Attendance Rules",
        "DB",
        "models/ShiftMaster.js, models/AttendanceRule.js",
        "DB",
        "Shift: name, start_time, end_time. Rules: late_mark_minutes, leave_types json.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Shift/Attendance Rules",
        "Backend",
        "CRUD /api/shifts, /api/attendance-rules",
        "Backend",
        "Feeds attendance + payroll deduction logic.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Shift/Attendance Rules",
        "Frontend",
        "pages/settings/attendance/ShiftList.jsx, AttendanceRulesForm.jsx",
        "Frontend",
        "Settings > Attendance Rules.",
        "Precious",
        "Medium",
        "Phase 1",
    ),
    task(
        "Package Master",
        "DB",
        "models/PackageMaster.js",
        "DB",
        "type (prepaid_bundle|membership), validity_days, price, included_services json, credit_count, discount_logic_json.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Package Master",
        "Backend",
        "CRUD /api/package-masters",
        "Backend",
        "routes/packageMasterRoutes.js",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Package Master",
        "Frontend",
        "pages/settings/packages/PackageMasterList.jsx, PackageMasterForm.jsx",
        "Frontend",
        "Define prepaid vs membership; credit count; discount logic JSON fields with UI helpers.",
        "Precious",
        "High",
        "Phase 1",
    ),
    section("ARNAV — CUSTOMER MASTER (CRM OWNER)"),
    task(
        "Customer Master",
        "DB",
        "models/Customer.js",
        "DB",
        "name, phone (unique), dob, anniversary_date, gender, tags[], preferred_stylist_id, notes, created_at.",
        "Arnav",
        "Critical",
        "Phase 1",
        notes="Precious uses GET/POST search API only in booking/billing screens.",
    ),
    task(
        "Customer Master",
        "Backend",
        "CRUD /api/customers + GET /api/customers/search?q=",
        "Backend",
        "Quick search for booking/billing; auto-create on first visit endpoint.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Customer Master",
        "Frontend",
        "components/customers/CustomerSearchOrCreate.jsx",
        "Frontend",
        "Shared component imported by Arnav bookings + Precious billing (Arnav owns file).",
        "Arnav",
        "Critical",
        "Phase 1",
        notes="Single owner prevents merge conflicts on customer UI.",
    ),
    section("PRECIOUS — WHATSAPP TEMPLATE MASTER"),
    task(
        "WhatsApp Template",
        "DB",
        "models/WhatsAppTemplate.js",
        "DB",
        "name, trigger_type, message_body, is_active.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "WhatsApp Template",
        "Backend",
        "CRUD /api/whatsapp-templates",
        "Backend",
        "Owner/Manager only.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "WhatsApp Template",
        "Frontend",
        "pages/settings/whatsapp/TemplateList.jsx, TemplateForm.jsx",
        "Frontend",
        "Pre-approved message templates for campaigns.",
        "Precious",
        "Medium",
        "Phase 1",
    ),
]

# ---------------------------------------------------------------------------
# 04 Bookings (Arnav)
# ---------------------------------------------------------------------------
SHEETS["04 Bookings"] = [
    section("BOOKINGS / APPOINTMENTS — PHASE 1 INTERNAL ONLY"),
    task(
        "Bookings",
        "DB",
        "models/Booking.js",
        "DB",
        "customer_id, branch_id, stylist_id, service_ids[], booking_date, start_time, end_time, status, source, created_by, notes.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Backend",
        "services/bookingConflictService.js",
        "Backend",
        "Stylist+date+time overlap check; return next available slot suggestion on conflict.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Backend",
        "CRUD /api/bookings + PATCH status",
        "Backend",
        "Status flow: booked→confirmed→in_progress→completed→no_show|cancelled. Walk-in = start_time now.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Backend",
        "GET /api/bookings/availability",
        "Backend",
        "Query stylist_id, date — return free slots.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Frontend",
        "pages/bookings/BookingList.jsx",
        "Frontend",
        "Today queue view for receptionist; filter by status/stylist.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Frontend",
        "pages/bookings/BookingForm.jsx",
        "Frontend",
        "Customer search-or-create, multi-service, stylist filtered by specialization, date/time, notes. Large touch targets.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Frontend",
        "pages/bookings/BookingCalendar.jsx",
        "Frontend",
        "Optional calendar view per stylist/day.",
        "Arnav",
        "Medium",
        "Phase 1",
    ),
    task(
        "Bookings",
        "Integration",
        "Link completed booking → billing handoff",
        "Frontend",
        "Button 'Create Invoice' passes booking_id to billing route (Precious billing reads query param).",
        "Arnav",
        "High",
        "Phase 1",
        notes="Contract: /billing/new?bookingId=xxx — Precious implements reader only.",
    ),
    section("PHASE 2 — ONLINE BOOKING (NOT NOW)"),
    task(
        "Online Booking",
        "Flag",
        "Customer self-booking web flow",
        "All",
        "Phase 2 — same slot engine, source=online. Do not build in Phase 1.",
        "Arnav",
        "Low",
        "Phase 3",
        status="Deferred",
    ),
]

# ---------------------------------------------------------------------------
# 05 Billing-POS-Inventory (Precious)
# ---------------------------------------------------------------------------
SHEETS["05 Billing-POS-Inventory"] = [
    section("BILLING / POS"),
    task(
        "Billing",
        "DB",
        "models/Invoice.js, models/InvoiceLineItem.js",
        "DB",
        "Invoice: totals, payment_mode, payment_status. LineItem: item_type, item_id, staff_id (per line!), package_redemption_id.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Billing",
        "Backend",
        "services/billingService.js",
        "Backend",
        "Create invoice atomically: line items, stock deduct, package redemption, commission entries.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Billing",
        "Backend",
        "POST /api/invoices",
        "Backend",
        "Supports split payment; GST line tax from TaxMaster; blocks product sale if insufficient stock.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Billing",
        "Backend",
        "Stock deduction + Manager override",
        "Backend",
        "Decrement ProductMaster.current_stock; require approve permission to force override; AuditLog entry.",
        "Precious",
        "Critical",
        "Phase 1",
        notes="Calls Arnav's product API/internal model read — no edits to product routes.",
    ),
    task(
        "Billing",
        "Backend",
        "Package redemption at billing",
        "Backend",
        "Reduce line to ₹0 or membership %; set package_redemption_id; decrement CustomerPackage.credits_remaining in transaction.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Billing",
        "Backend",
        "models/CommissionEntry.js + write on invoice save",
        "Backend",
        "Per line staff_id commission accrual for flat/tiered types (threshold type deferred to payroll).",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Billing",
        "Frontend",
        "pages/billing/PosScreen.jsx",
        "Frontend",
        "Touchscreen-friendly POS: customer, line items, per-line staff, package toggle, payment split. Dead simple UX.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Billing",
        "Frontend",
        "pages/billing/InvoiceList.jsx, InvoiceDetail.jsx",
        "Frontend",
        "GST-compliant invoice display/print view.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Billing",
        "Frontend",
        "components/billing/PaymentSplitModal.jsx",
        "Frontend",
        "Cash + UPI + card split amounts.",
        "Precious",
        "Medium",
        "Phase 1",
    ),
    section("INVENTORY (OPERATIONAL)"),
    task(
        "Inventory",
        "Backend",
        "GET /api/inventory/stock-report",
        "Backend",
        "Current stock, reorder alerts — read from ProductMaster.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Inventory",
        "Frontend",
        "pages/inventory/StockOverview.jsx",
        "Frontend",
        "Low stock highlights; link to product settings (Arnav's screen).",
        "Precious",
        "Medium",
        "Phase 1",
    ),
]

# ---------------------------------------------------------------------------
# 06 Attendance-Payroll (Precious = Attendance, Arnav = Payroll)
# ---------------------------------------------------------------------------
SHEETS["06 Attendance-Payroll"] = [
    section("PRECIOUS — ATTENDANCE"),
    task(
        "Attendance",
        "DB",
        "models/Attendance.js",
        "DB",
        "staff_id, date, punch_in_time, punch_out_time, status, remarks, punched_by.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Attendance",
        "Backend",
        "POST /api/attendance/punch-in, /punch-out",
        "Backend",
        "One open punch-in per staff per day; admin punch on behalf logs punched_by.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Attendance",
        "Backend",
        "GET /api/attendance/today, /api/attendance/summary",
        "Backend",
        "Staff on duty for dashboard; monthly summary for payroll.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Attendance",
        "Frontend",
        "pages/attendance/PunchScreen.jsx",
        "Frontend",
        "Single Punch In/Out toggle; tablet-friendly; staff self-select.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Attendance",
        "Frontend",
        "pages/attendance/AttendanceLog.jsx",
        "Frontend",
        "Manager view of daily/monthly attendance.",
        "Precious",
        "High",
        "Phase 1",
    ),
    section("ARNAV — PAYROLL & COMMISSION ENGINE"),
    task(
        "Commission",
        "Backend",
        "services/commissionService.js — calculateCommission(staff_id, period)",
        "Backend",
        "Strategies: threshold_bonus, flat_pct, tiered, flat_by_item_type from CommissionSlab.rules_json.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Commission",
        "Backend",
        "Commission Settings CRUD /api/commission-settings",
        "Backend",
        "Owner edits slab rules via UI config — not hardcoded.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Commission",
        "Frontend",
        "pages/settings/commission/CommissionSettings.jsx",
        "Frontend",
        "Edit multiplier, bonus %, tier breakpoints per slab.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Payroll",
        "DB",
        "models/PayrollRun.js, models/PayrollEntry.js",
        "DB",
        "Run: month, year, status (draft|finalized|paid). Entry: base_salary, commission_total, deductions, net_payable.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Payroll",
        "Backend",
        "services/payrollService.js",
        "Backend",
        "base + commission (incl. month-end threshold bonus) + attendance deductions from Precious's summary API.",
        "Arnav",
        "Critical",
        "Phase 2",
        notes="Consumes GET /api/attendance/summary — no edits to attendance files.",
    ),
    task(
        "Payroll",
        "Backend",
        "POST /api/payroll/runs, PATCH finalize",
        "Backend",
        "Manager view-only; Owner finalizes. Slab changes don't retroactive finalized runs.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Payroll",
        "Backend",
        "Export payroll Excel/PDF",
        "Backend",
        "GET /api/payroll/runs/:id/export?format=xlsx|pdf",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Payroll",
        "Frontend",
        "pages/payroll/PayrollRunList.jsx, PayrollRunDetail.jsx",
        "Frontend",
        "Generate draft, review entries, finalize, export.",
        "Arnav",
        "High",
        "Phase 2",
    ),
]

# ---------------------------------------------------------------------------
# 07 CRM-WhatsApp (Arnav = CRM, Precious = WhatsApp automation)
# ---------------------------------------------------------------------------
SHEETS["07 CRM-WhatsApp"] = [
    section("ARNAV — CRM & VISIT LOG"),
    task(
        "Visit Log",
        "Backend",
        "Auto-create visit log on booking completed / invoice paid",
        "Backend",
        "Hook in booking status listener + billing callback event. visit date, services, staff, amount, rating.",
        "Arnav",
        "High",
        "Phase 1",
        notes="Event contract documented in README — Precious emits invoice.paid event from billingService.",
    ),
    task(
        "CRM",
        "DB",
        "models/CustomerVisitLog.js (or embedded visits[])",
        "DB",
        "visit_date, services, staff_ids, amount, feedback_rating.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "CRM",
        "Backend",
        "GET /api/customers/:id/profile",
        "Backend",
        "Visit history, active packages (read from Precious API), preferences, tags.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "CRM",
        "Backend",
        "services/customerSegmentationService.js",
        "Backend",
        "Nightly job: birthday this week, anniversary, inactive 45+/60+, high-value, package expiring.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "CRM",
        "Backend",
        "Customer tags — manual vs system",
        "Backend",
        "tags[].type = manual|system; system tags recomputed nightly.",
        "Arnav",
        "Medium",
        "Phase 2",
    ),
    task(
        "CRM",
        "Frontend",
        "pages/crm/CustomerProfile.jsx",
        "Frontend",
        "Read view: history, packages, preferences; manual vs system tags visually distinct.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "CRM",
        "Frontend",
        "pages/crm/SegmentList.jsx",
        "Frontend",
        "View segments with counts; launch campaign hands off to Precious campaign screen.",
        "Arnav",
        "Medium",
        "Phase 2",
    ),
    section("PRECIOUS — WHATSAPP AUTOMATION"),
    task(
        "WhatsApp API",
        "External",
        "Meta WhatsApp Business API application",
        "External",
        "Start business verification immediately — longest lead time. Document WABA credentials in .env.",
        "Precious",
        "Critical",
        "Phase 1",
        notes="Parallel track — not blocked on code.",
    ),
    task(
        "WhatsApp",
        "DB",
        "models/WhatsAppCampaignLog.js, models/MessageQueue.js",
        "DB",
        "Queue table for scheduled sends; log sent/delivered/read/failed.",
        "Precious",
        "High",
        "Phase 2",
    ),
    task(
        "WhatsApp",
        "Backend",
        "services/whatsappService.js",
        "Backend",
        "Cloud API send; template variable substitution.",
        "Precious",
        "Critical",
        "Phase 2",
    ),
    task(
        "WhatsApp",
        "Backend",
        "jobs/campaignScheduler.js",
        "Backend",
        "Cron: birthday, anniversary, appointment reminders, package expiry, win-back. Async — not sync from UI.",
        "Precious",
        "Critical",
        "Phase 2",
    ),
    task(
        "WhatsApp",
        "Backend",
        "POST /api/campaigns/preview, POST /api/campaigns/send",
        "Backend",
        "Preview audience count; queue campaign messages.",
        "Precious",
        "High",
        "Phase 2",
    ),
    task(
        "WhatsApp",
        "Frontend",
        "pages/crm/CampaignScreen.jsx",
        "Frontend",
        "Select trigger, template, preview count, schedule/send now. Owner/Manager only.",
        "Precious",
        "High",
        "Phase 2",
    ),
]

# ---------------------------------------------------------------------------
# 08 Packages (Precious)
# ---------------------------------------------------------------------------
SHEETS["08 Packages"] = [
    section("PACKAGE SALE & REDEMPTION"),
    task(
        "Packages",
        "DB",
        "models/CustomerPackage.js",
        "DB",
        "customer_id, package_master_id, purchase_date, expiry_date, credits_remaining, status, invoice_id.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Packages",
        "Backend",
        "POST /api/customer-packages/sale",
        "Backend",
        "Create CustomerPackage with expiry + credits from PackageMaster.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Packages",
        "Backend",
        "GET /api/customers/:id/packages/active",
        "Backend",
        "List active packages/credits for billing redemption UI.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Packages",
        "Frontend",
        "pages/packages/PackageSale.jsx",
        "Frontend",
        "Customer, package select, payment — creates CustomerPackage.",
        "Precious",
        "High",
        "Phase 1",
    ),
    task(
        "Packages",
        "Frontend",
        "pages/packages/CustomerPackageList.jsx",
        "Frontend",
        "View active/expired/exhausted packages per customer.",
        "Precious",
        "Medium",
        "Phase 1",
    ),
    task(
        "Packages",
        "Business rule",
        "Confirm package interpretation with client",
        "All",
        "Before redemption logic: single-service bundle vs credit pool vs straight discount. See Technical Spec §4.",
        "Both",
        "Critical",
        "Phase 1",
        status="Blocked",
        notes="Client meeting item — do not guess.",
    ),
    task(
        "Packages",
        "Backend",
        "Expiry/low-credit alert triggers",
        "Backend",
        "Emit events for WhatsApp scheduler when credits low or expiry within N days.",
        "Precious",
        "Medium",
        "Phase 2",
    ),
]

# ---------------------------------------------------------------------------
# 09 Reports-Dashboard (split)
# ---------------------------------------------------------------------------
SHEETS["09 Reports-Dashboard"] = [
    section("ARNAV — DASHBOARD (SHOWSTOPPER)"),
    task(
        "Dashboard",
        "Frontend",
        "pages/dashboard/OwnerDashboard.jsx",
        "Frontend",
        "Hero greeting, business-health score, KPI cards, charts — executive cockpit style.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Dashboard",
        "Backend",
        "GET /api/dashboard/kpis",
        "Backend",
        "Today's revenue, bookings, walk-ins vs appointments, active packages, staff on duty — aggregates from both modules.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Dashboard",
        "Frontend",
        "pages/dashboard/ReceptionistDashboard.jsx",
        "Frontend",
        "Today's booking queue + quick billing shortcut only.",
        "Arnav",
        "High",
        "Phase 1",
    ),
    task(
        "Dashboard",
        "Frontend",
        "Chart widgets — revenue trend, category split, staff leaderboard, booking funnel",
        "Frontend",
        "Recharts/Chart.js components in components/dashboard/.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    section("ARNAV — REPORTS"),
    task(
        "Reports",
        "Backend+Frontend",
        "Revenue Report (daily/monthly, services vs products)",
        "All",
        "pages/reports/RevenueReport.jsx + GET /api/reports/revenue. Date range filter, Excel/PDF export.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Reports",
        "Backend+Frontend",
        "Staff Performance Report (leaderboard)",
        "All",
        "pages/reports/StaffPerformanceReport.jsx + GET /api/reports/staff-performance.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Reports",
        "Backend+Frontend",
        "Customer Retention Report",
        "All",
        "Repeat vs new, churn/inactive list. pages/reports/RetentionReport.jsx.",
        "Arnav",
        "Medium",
        "Phase 2",
    ),
    section("PRECIOUS — REPORTS"),
    task(
        "Reports",
        "Backend+Frontend",
        "Attendance Summary Report",
        "All",
        "pages/reports/AttendanceReport.jsx + GET /api/reports/attendance.",
        "Precious",
        "High",
        "Phase 2",
    ),
    task(
        "Reports",
        "Backend+Frontend",
        "Inventory Stock / Reorder Report",
        "All",
        "pages/reports/InventoryReport.jsx + GET /api/reports/inventory.",
        "Precious",
        "High",
        "Phase 2",
    ),
    task(
        "Reports",
        "Backend+Frontend",
        "Package Sales & Redemption Report",
        "All",
        "pages/reports/PackageReport.jsx + GET /api/reports/packages.",
        "Precious",
        "Medium",
        "Phase 2",
    ),
    task(
        "Reports",
        "Backend+Frontend",
        "Campaign Performance Report",
        "All",
        "WhatsApp open/response if API provides. pages/reports/CampaignReport.jsx.",
        "Precious",
        "Medium",
        "Phase 2",
    ),
    task(
        "Reports",
        "Shared",
        "components/reports/ReportFilterBar.jsx + exportUtils.js",
        "Frontend",
        "Date range, staff filter, category filter, Excel/PDF export. Precious owns file; Arnav imports.",
        "Precious",
        "High",
        "Phase 2",
        notes="Single owner for shared report components.",
    ),
]

# ---------------------------------------------------------------------------
# 10 Phases-Acceptance
# ---------------------------------------------------------------------------
SHEETS["10 Phases-Acceptance"] = [
    section("PHASE 0 — FOUNDATION (WEEK 1)"),
    task(
        "Phase 0",
        "Foundation",
        "Scaffold + DB + Auth + RBAC seeds",
        "All",
        "Arnav delivers; Precious reviews PR before branching.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    task(
        "Phase 0",
        "Foundation",
        "Route split (arnavRoutes / preciousRoutes) merged",
        "All",
        "Both devs can mount modules without touching same router file.",
        "Both",
        "Critical",
        "Phase 0",
    ),
    task(
        "Phase 0",
        "Done When",
        "Owner logs in; sees role-based menu; User CRUD works",
        "All",
        "Exit criteria Phase 0.",
        "Arnav",
        "Critical",
        "Phase 0",
    ),
    section("PHASE 1 — CORE OPS (WEEK 2-5)"),
    task(
        "Phase 1",
        "Masters",
        "All Phase 1 masters seeded and CRUD working",
        "All",
        "Arnav: services, products, tax, customers. Precious: staff, shifts, package masters, WA templates.",
        "Both",
        "Critical",
        "Phase 1",
    ),
    task(
        "Phase 1",
        "Transactions",
        "Internal booking end-to-end",
        "All",
        "Create booking → conflict check → status updates → handoff to billing.",
        "Arnav",
        "Critical",
        "Phase 1",
    ),
    task(
        "Phase 1",
        "Transactions",
        "POS billing end-to-end",
        "All",
        "Invoice with services+products, stock deduct, package redemption, split payment, GST invoice.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Phase 1",
        "Transactions",
        "Attendance punch + package sale",
        "All",
        "Punch in/out; sell package; redeem at POS.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "Phase 1",
        "Done When",
        "Front-desk can book, bill, punch, sell package in one day flow",
        "All",
        "Exit criteria Phase 1.",
        "Both",
        "Critical",
        "Phase 1",
    ),
    section("PHASE 2 — PAYROLL, CRM, REPORTS, DASHBOARD (WEEK 6-9)"),
    task(
        "Phase 2",
        "Payroll",
        "Monthly payroll run with commission + attendance deductions",
        "All",
        "Threshold bonus at month-end; export Excel/PDF.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Phase 2",
        "CRM",
        "Segmentation + visit log + customer profile complete",
        "All",
        "Inactive tags, birthday segments visible.",
        "Arnav",
        "High",
        "Phase 2",
    ),
    task(
        "Phase 2",
        "WhatsApp",
        "Automated campaigns live (至少 appointment reminder + birthday)",
        "All",
        "Queue-based send via Business API.",
        "Precious",
        "High",
        "Phase 2",
    ),
    task(
        "Phase 2",
        "Dashboard",
        "Owner dashboard 'showstopper' complete",
        "All",
        "All KPI cards and charts populated with real data.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "Phase 2",
        "Reports",
        "All 7 report types exportable",
        "All",
        "Revenue, staff, attendance, inventory, retention, packages, campaigns.",
        "Both",
        "High",
        "Phase 2",
    ),
    task(
        "Phase 2",
        "Done When",
        "Owner sees full dashboard; payroll finalized; WhatsApp birthday campaign sent",
        "All",
        "Exit criteria Phase 2.",
        "Both",
        "Critical",
        "Phase 2",
    ),
    section("PHASE 3 — FUTURE (POST CLIENT SIGN-OFF)"),
    task(
        "Phase 3",
        "Online booking",
        "Customer-facing booking web/PWA",
        "All",
        "source=online into same slot engine.",
        "Arnav",
        "Medium",
        "Phase 3",
        status="Deferred",
    ),
    task(
        "Phase 3",
        "Biometric attendance",
        "InsightFace / biometric punch",
        "All",
        "Reuse Celeris HRMS pattern if client wants upsell.",
        "Precious",
        "Low",
        "Phase 3",
        status="Deferred",
    ),
    task(
        "Phase 3",
        "Receptionist role",
        "Seed Receptionist role + permissions",
        "All",
        "If client hires dedicated front-desk staff.",
        "Arnav",
        "Low",
        "Phase 3",
        status="Deferred",
    ),
    section("CLIENT MEETING — OPEN ITEMS"),
    task(
        "Client",
        "Discovery",
        "Exact service list & pricing for seed data",
        "All",
        "Service Master seed.",
        "Both",
        "Critical",
        "Phase 1",
        status="Blocked",
    ),
    task(
        "Client",
        "Discovery",
        "Current system: manual vs existing software?",
        "All",
        "Migration effort estimate.",
        "Both",
        "High",
        "Phase 1",
        status="Blocked",
    ),
    task(
        "Client",
        "Discovery",
        "Staff count for commission/payroll estimate",
        "All",
        None,
        "Both",
        "High",
        "Phase 1",
        status="Blocked",
    ),
    task(
        "Client",
        "Discovery",
        "Customer-facing booking in Phase 1?",
        "All",
        "Validate internal-first assumption.",
        "Both",
        "Medium",
        "Phase 1",
        status="Blocked",
    ),
    task(
        "Client",
        "Discovery",
        "WhatsApp number: new business vs existing",
        "All",
        "WABA setup.",
        "Precious",
        "High",
        "Phase 1",
        status="Blocked",
    ),
    task(
        "Client",
        "Discovery",
        "Package interpretation: buy 2 get 1 free example",
        "All",
        "Real rupee amounts + service names before redemption build.",
        "Both",
        "Critical",
        "Phase 1",
        status="Blocked",
    ),
    section("ACCEPTANCE CRITERIA (UAT)"),
    task(
        "UAT",
        "Security",
        "Receptionist API direct call returns 403 for reports",
        "Backend",
        "Server-side RBAC enforced — not just hidden menu.",
        "Arnav",
        "Critical",
        "Phase 2",
    ),
    task(
        "UAT",
        "Billing",
        "Multi-stylist invoice attributes commission per line",
        "Backend",
        "InvoiceLineItem.staff_id per line verified.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "UAT",
        "Packages",
        "Redemption audit trail links invoice line to CustomerPackage",
        "Backend",
        "No silent credit decrement.",
        "Precious",
        "Critical",
        "Phase 1",
    ),
    task(
        "UAT",
        "UX",
        "Booking + billing completable in minimal taps on tablet",
        "Frontend",
        "Front-desk usability sign-off with client.",
        "Both",
        "Critical",
        "Phase 2",
    ),
]


def count_tasks(rows: list[tuple]) -> int:
    return sum(1 for r in rows if r[2] is not None)


def build_overview() -> list[tuple]:
    rows = [
        (
            "Salon Management System — Implementation Tracker",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        (
            "Source: Implementation Guide + Technical Spec | MERN + PWA | Arnav + Precious",
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
        ),
        (None,) * 10,
        ("Sheet", "Scope", "Item Count", "Primary Owner", None, None, None, None, None, None),
    ]
    owners = {
        "01 Architecture-Foundation": "Arnav (scaffold) + shared routing contract",
        "02 RBAC-User-Management": "Arnav",
        "03 Masters-Settings": "Split — see sheet",
        "04 Bookings": "Arnav",
        "05 Billing-POS-Inventory": "Precious",
        "06 Attendance-Payroll": "Precious (attendance) + Arnav (payroll)",
        "07 CRM-WhatsApp": "Arnav (CRM) + Precious (WhatsApp)",
        "08 Packages": "Precious",
        "09 Reports-Dashboard": "Split — see sheet",
        "10 Phases-Acceptance": "Both",
    }
    scopes = {
        "01 Architecture-Foundation": "MERN scaffold, merge-safe routing, branch schema, seeds, audit log",
        "02 RBAC-User-Management": "Step zero: roles, permissions, login, user mgmt, staff self-service views",
        "03 Masters-Settings": "Service/Product/Tax/Customer (Arnav); Staff/Shift/Package/WA Template (Precious)",
        "04 Bookings": "Internal bookings Phase 1, conflict engine, walk-ins, billing handoff",
        "05 Billing-POS-Inventory": "POS, invoices, stock deduct, commission entries, GST, inventory views",
        "06 Attendance-Payroll": "Punch attendance (Precious); commission engine + payroll run (Arnav)",
        "07 CRM-WhatsApp": "Visit log, segmentation, customer profile (Arnav); WABA campaigns (Precious)",
        "08 Packages": "CustomerPackage sale/redemption, client interpretation gate",
        "09 Reports-Dashboard": "Owner dashboard + revenue/staff/retention (Arnav); attendance/inventory/package/campaign reports (Precious)",
        "10 Phases-Acceptance": "Phase 0-3 milestones, client open items, UAT criteria",
    }
    total = 0
    for name in [
        "01 Architecture-Foundation",
        "02 RBAC-User-Management",
        "03 Masters-Settings",
        "04 Bookings",
        "05 Billing-POS-Inventory",
        "06 Attendance-Payroll",
        "07 CRM-WhatsApp",
        "08 Packages",
        "09 Reports-Dashboard",
        "10 Phases-Acceptance",
    ]:
        c = count_tasks(SHEETS[name])
        total += c
        rows.append((name, scopes[name], c, owners[name], None, None, None, None, None, None))
    rows.append((None,) * 10)
    rows.append(("TOTAL TASKS", None, total, None, None, None, None, None, None, None))
    rows.append((None,) * 10)
    rows.append(("MERGE-CONFLICT RULES", None, None, None, None, None, None, None, None, None))
    rules = [
        "1. Arnav owns backend/routes/arnavRoutes.js + frontend/src/routes/arnavRoutes.jsx — Precious owns preciousRoutes equivalents.",
        "2. Never edit the other dev's route aggregator; register new routes only in your own file.",
        "3. Shared components have a single owner (noted in Notes column) — import, don't duplicate.",
        "4. Customer model + CustomerSearchOrCreate.jsx = Arnav. Precious consumes APIs only.",
        "5. ProductMaster = Arnav. Stock deduction logic = Precious billingService only.",
        "6. Phase 0 scaffold merged by Arnav before Precious starts feature branches.",
        "7. Cross-module contracts (bookingId handoff, invoice.paid event) documented in README — agree before coding.",
    ]
    for r in rules:
        rows.append((r, None, None, None, None, None, None, None, None, None))
    return rows


def write_sheet(ws, rows: list[tuple], is_overview: bool = False) -> None:
    header_font = Font(bold=True)
    header_fill = PatternFill("solid", fgColor="D9E1F2")
    section_fill = PatternFill("solid", fgColor="F2F2F2")
    section_font = Font(bold=True)

    for col, h in enumerate(HEADERS, 1):
        cell = ws.cell(1, col, h)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(vertical="center", wrap_text=True)

    for r_idx, row in enumerate(rows, 2):
        for c_idx, val in enumerate(row, 1):
            cell = ws.cell(r_idx, c_idx, val)
            cell.alignment = Alignment(vertical="top", wrap_text=True)
        # Section header row: only col A filled, rest empty
        if row[0] and row[2] is None and row[1] is None:
            for c in range(1, 11):
                ws.cell(r_idx, c).fill = section_fill
            ws.cell(r_idx, 1).font = section_font

    widths = [28, 22, 42, 12, 55, 12, 14, 10, 12, 40]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w
    ws.freeze_panes = "A2"


def export_csv(sheet_name: str, rows: list[tuple]) -> None:
    CSV_DIR.mkdir(parents=True, exist_ok=True)
    safe = sheet_name.replace(" ", "_")
    path = CSV_DIR / f"{safe}.csv"
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(HEADERS)
        for row in rows:
            writer.writerow(row)


def main() -> None:
    wb = Workbook()
    # Overview
    ov = wb.active
    ov.title = "00 Overview"
    overview_rows = build_overview()
    write_sheet(ov, overview_rows, is_overview=True)
    export_csv("00 Overview", overview_rows)

    for sheet_name, rows in SHEETS.items():
        ws = wb.create_sheet(sheet_name)
        write_sheet(ws, rows)
        export_csv(sheet_name, rows)

    wb.save(XLSX_PATH)
    print(f"Wrote {XLSX_PATH}")
    print(f"Wrote CSVs to {CSV_DIR}")
    print(f"Total tasks: {sum(count_tasks(SHEETS[s]) for s in SHEETS)}")


if __name__ == "__main__":
    main()
